package org.duc.conceptualbank.entity;
// Generated Feb 7, 2018 5:37:51 PM by Hibernate Tools 5.2.8.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Branches generated by hbm2java
 */
@Entity
@Table(name = "branches", catalog = "conceptual_bank")
public class Branches implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer branchCode;
	private Cities cities;
	private String headofficeYn;
	private String branchDetails;
	private Set<Accounts> accountses = new HashSet<Accounts>(0);

	public Branches() {
	}

	public Branches(Cities cities, String headofficeYn) {
		this.cities = cities;
		this.headofficeYn = headofficeYn;
	}

	public Branches(Cities cities, String headofficeYn, String branchDetails, Set<Accounts> accountses) {
		this.cities = cities;
		this.headofficeYn = headofficeYn;
		this.branchDetails = branchDetails;
		this.accountses = accountses;
	}

	public Branches(Cities cities, String headofficeYn, String branchDetails) {
		this.cities = cities;
		this.headofficeYn = headofficeYn;
		this.branchDetails = branchDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "branch_code", unique = true, nullable = false)
	public Integer getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(Integer branchCode) {
		this.branchCode = branchCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "city_code", nullable = false)
	public Cities getCities() {
		return this.cities;
	}

	public void setCities(Cities cities) {
		this.cities = cities;
	}

	@Column(name = "headoffice_yn", nullable = false, length = 45)
	public String getHeadofficeYn() {
		return this.headofficeYn;
	}

	public void setHeadofficeYn(String headofficeYn) {
		this.headofficeYn = headofficeYn;
	}

	@Column(name = "branch_details", length = 45)
	public String getBranchDetails() {
		return this.branchDetails;
	}

	public void setBranchDetails(String branchDetails) {
		this.branchDetails = branchDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "branches", cascade = CascadeType.ALL)
	public Set<Accounts> getAccountses() {
		return this.accountses;
	}

	public void setAccountses(Set<Accounts> accountses) {
		this.accountses = accountses;
	}

	public String toString() {
		return "Branch code: " + branchCode + "\tCity code: " + cities.getCityCode() + "\tHead office: " + headofficeYn
				+ "\tBranch details: " + branchDetails;
	}
}
