package org.duc.conceptualbank.entity;
// Generated Feb 7, 2018 5:37:51 PM by Hibernate Tools 5.2.8.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Cities generated by hbm2java
 */
@Entity
@Table(name = "cities", catalog = "conceptual_bank")
@Proxy(lazy = false)
public class Cities implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer cityCode;
	private String cityName;
	private Set<Branches> brancheses = new HashSet<Branches>(0);

	public Cities() {
	}

	public Cities(String cityName) {
		this.cityName = cityName;
	}

	public Cities(String cityName, Set<Branches> brancheses) {
		this.cityName = cityName;
		this.brancheses = brancheses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "city_code", unique = true, nullable = false)
	public Integer getCityCode() {
		return this.cityCode;
	}

	public void setCityCode(Integer cityCode) {
		this.cityCode = cityCode;
	}

	@Column(name = "city_name", nullable = false, length = 45)
	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cities", cascade = CascadeType.ALL)
	@JsonIgnore
	public Set<Branches> getBrancheses() {
		return this.brancheses;
	}

	public void setBrancheses(Set<Branches> brancheses) {
		this.brancheses = brancheses;
	}

	public String toString() {
		return "City code: " + cityCode + "\tCity name: " + cityName;
	}
}
