package org.duc.conceptualbank.entity;
// Generated Feb 7, 2018 5:37:51 PM by Hibernate Tools 5.2.8.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * CustomerType generated by hbm2java
 */
@Entity
@Table(name = "customer_type", catalog = "conceptual_bank")
@Proxy(lazy = false)
public class CustomerType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer customerTypeCode;
	private String customerTypeDescription;
	private Set<Customers> customerses = new HashSet<Customers>(0);

	public CustomerType() {
	}

	public CustomerType(String customerTypeDescription) {
		this.customerTypeDescription = customerTypeDescription;
	}

	public CustomerType(String customerTypeDescription, Set<Customers> customerses) {
		this.customerTypeDescription = customerTypeDescription;
		this.customerses = customerses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "customer_type_code", unique = true, nullable = false)
	public Integer getCustomerTypeCode() {
		return this.customerTypeCode;
	}

	public void setCustomerTypeCode(Integer customerTypeCode) {
		this.customerTypeCode = customerTypeCode;
	}

	@Column(name = "customer_type_description", nullable = false, length = 45)
	public String getCustomerTypeDescription() {
		return this.customerTypeDescription;
	}

	public void setCustomerTypeDescription(String customerTypeDescription) {
		this.customerTypeDescription = customerTypeDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerType", cascade = CascadeType.ALL)
	@JsonIgnore
	public Set<Customers> getCustomerses() {
		return this.customerses;
	}

	public void setCustomerses(Set<Customers> customerses) {
		this.customerses = customerses;
	}

	public String toString() {
		return "Customer type code: " + customerTypeCode + "\tCustomer type description: " + customerTypeDescription;
	}
}
